import React, { useState, useEffect } from 'react';
import { Youtube, Headphones, Radio, Music2, Linkedin, ExternalLink, BookOpen, RefreshCw } from 'lucide-react';

// ─── Substack RSS Types ──────────────────────────────────────────────────────
interface SubstackArticle {
  title: string;
  link: string;
  pubDate: string;
  description: string; // HTML snippet
  thumbnail?: string;
  author?: string;
  categories?: string[];
}

// Static feed JSON is generated by GitHub Actions (.github/workflows/fetch-substack.yml)
// and served from the same domain — no CORS issues possible.
const FEED_URL = `${import.meta.env.BASE_URL}substack-feed.json`;

// Strip HTML tags to get plain-text excerpt
function stripHtml(html: string): string {
  const div = document.createElement('div');
  div.innerHTML = html;
  return div.textContent || div.innerText || '';
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}


// ─── SubstackFeed Component ───────────────────────────────────────────────────
function SubstackFeed() {
  const [articles, setArticles] = useState<SubstackArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);

  const fetchFeed = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(FEED_URL);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (data.status !== 'ok' || !data.items?.length) throw new Error('Feed unavailable');
      setArticles(data.items);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load articles');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchFeed(); }, []);

  const visible = showAll ? articles : articles.slice(0, 1);

  if (loading) {
    return (
      <div className="space-y-6">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="bg-white rounded-2xl border border-vintage-border p-8 animate-pulse">
            <div className="h-3 bg-vintage-border rounded w-24 mb-4" />
            <div className="h-6 bg-vintage-border rounded w-3/4 mb-3" />
            <div className="h-3 bg-vintage-border rounded w-full mb-2" />
            <div className="h-3 bg-vintage-border rounded w-5/6 mb-2" />
            <div className="h-3 bg-vintage-border rounded w-2/3" />
          </div>
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="font-serif italic text-vintage-black/60 mb-4">Unable to load articles right now.</p>
        <button
          onClick={fetchFeed}
          className="inline-flex items-center gap-2 px-5 py-2 rounded-full border border-vintage-border bg-white text-vintage-black/70 hover:text-vintage-red hover:border-vintage-red transition-all text-sm font-sans uppercase tracking-wider cursor-pointer"
        >
          <RefreshCw size={14} /> Try Again
        </button>
      </div>
    );
  }

  if (articles.length === 0) {
    return (
      <p className="text-center font-serif italic text-vintage-black/50 py-8">
        No articles published yet.
      </p>
    );
  }

  return (
    <div className="space-y-8">
      {visible.map((article, index) => {
        const excerpt = stripHtml(article.description).slice(0, 280).trim();
        return (
          <article
            key={article.link}
            className="group bg-white rounded-2xl border border-vintage-border shadow-sm hover:shadow-md hover:border-vintage-black/20 transition-all duration-500 overflow-hidden"
          >
            {/* Category tag row */}
            <div className="px-8 pt-6 flex items-center justify-between">
              <span className="font-sans text-xs tracking-[0.2em] uppercase text-vintage-red font-semibold">
                {index === 0 ? 'Latest Article' : `Article`}
              </span>
              <time className="font-sans text-xs text-vintage-black/40 tracking-wide">
                {formatDate(article.pubDate)}
              </time>
            </div>

            <div className="px-8 pb-8 pt-3">
              <h3 className="font-serif text-2xl font-bold text-vintage-black mb-3 group-hover:text-vintage-red transition-colors duration-300 leading-snug">
                {article.title}
              </h3>

              {article.author && (
                <div className="mb-4">
                  <span className="font-sans text-xs tracking-widest uppercase text-vintage-black/60 font-medium pb-1 border-b border-vintage-red/30">
                    By {article.author}
                  </span>
                </div>
              )}

              {/* Decorative divider */}
              <div className="flex items-center gap-3 mb-4">
                <div className="h-px bg-vintage-border flex-1" />
                <BookOpen size={12} className="text-vintage-black/30" />
                <div className="h-px bg-vintage-border flex-1" />
              </div>

              <p className="font-serif text-base leading-relaxed text-vintage-black/75 mb-6">
                {excerpt}{excerpt.length >= 280 ? '…' : ''}
              </p>

              <a
                href={article.link}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 font-sans text-xs tracking-[0.2em] uppercase font-semibold text-vintage-red hover:text-vintage-black transition-colors duration-200 group/link"
              >
                Read on Substack
                <ExternalLink size={12} className="group-hover/link:translate-x-0.5 group-hover/link:-translate-y-0.5 transition-transform duration-200" />
              </a>
            </div>
          </article>
        );
      })}

      {articles.length > 1 && (
        <div className="flex justify-center mt-4">
          <button
            onClick={() => setShowAll(!showAll)}
            className="flex items-center gap-2 px-6 py-3 rounded-full border border-vintage-border bg-white text-vintage-black/70 hover:text-vintage-red hover:border-vintage-red transition-all shadow-sm font-sans text-sm font-medium uppercase tracking-wider cursor-pointer"
          >
            {showAll ? 'Show Less' : `Show ${articles.length - 1} More Article${articles.length > 2 ? 's' : ''}`}
            <span className={`transition-transform duration-300 ${showAll ? 'rotate-180' : ''}`}>
              ▾
            </span>
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function App() {

  return (
    <div className="min-h-screen flex flex-col items-center selection:bg-vintage-red selection:text-vintage-cream bg-vintage-cream text-vintage-black">
      
      {/* Top Border Accent */}
      <div className="w-full h-2 bg-vintage-red"></div>
      <div className="w-full h-px bg-vintage-black mt-1"></div>

      <main className="w-full max-w-5xl px-6 py-16 md:py-24 z-10 flex flex-col items-center">
        
        {/* Header Section */}
        <header className="text-center mb-20 w-full">
          <div className="flex flex-col items-center justify-center mb-8">
            <div className="w-full max-w-2xl border-t border-b border-vintage-black py-8 relative">
              {/* Decorative corner accents */}
              <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-vintage-black -mt-[1px] -ml-[1px]"></div>
              <div className="absolute top-0 right-0 w-2 h-2 border-t border-r border-vintage-black -mt-[1px] -mr-[1px]"></div>
              <div className="absolute bottom-0 left-0 w-2 h-2 border-b border-l border-vintage-black -mb-[1px] -ml-[1px]"></div>
              <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-vintage-black -mb-[1px] -mr-[1px]"></div>
              
              <h1 className="font-serif text-5xl md:text-7xl lg:text-8xl font-black text-vintage-red tracking-widest uppercase leading-none">
                Beating<br />Sisyphus
              </h1>
            </div>
          </div>
          
          <p className="font-serif text-xl md:text-2xl italic text-vintage-black max-w-2xl mx-auto font-medium">
            "How emerging markets overcome the impossible."
          </p>
        </header>

        {/* Listen On Section */}
        <section className="w-full mb-24">
          <div className="flex items-center justify-center gap-6 mb-10 w-full max-w-2xl mx-auto">
            <div className="h-px bg-vintage-border flex-1"></div>
            <h2 className="font-sans text-sm tracking-[0.3em] uppercase text-vintage-black/60 font-semibold">
              Available On
            </h2>
            <div className="h-px bg-vintage-border flex-1"></div>
          </div>
          
          <div className="flex flex-wrap justify-center gap-4 md:gap-6">
            <PlatformLink 
              href="https://youtube.com/playlist?list=PLsusrzm7-OaTbS2kVoUfYs78COGlG85wf&si=tw2DmU1HmtYRqocG"
              icon={<Youtube size={20} strokeWidth={1.5} />}
              name="YouTube"
            />
            <PlatformLink 
              href="https://open.spotify.com/show/7DOx0zfgbVNiluDSoQJCmI"
              icon={<Headphones size={20} strokeWidth={1.5} />}
              name="Spotify"
            />
            <PlatformLink 
              href="https://podcasts.apple.com/us/podcast/beating-sisyphus-how-emerging-markets-overcome-the/id1855339237"
              icon={<Radio size={20} strokeWidth={1.5} />}
              name="Apple Podcasts"
            />
            <PlatformLink 
              href="https://music.amazon.com/podcasts/eaafd303-1fc3-47a2-ad3b-655c19be7dd1/beating-sisyphus-how-emerging-markets-overcome-the-impossible"
              icon={<Music2 size={20} strokeWidth={1.5} />}
              name="Amazon Music"
            />
          </div>
        </section>

        {/* Episodes Section */}
        <section className="w-full mb-24">
          <div className="flex items-center justify-center gap-6 mb-12 w-full max-w-2xl mx-auto">
            <div className="h-px bg-vintage-border flex-1"></div>
            <h2 className="font-serif text-3xl md:text-4xl italic text-vintage-black">
              Latest Episodes
            </h2>
            <div className="h-px bg-vintage-border flex-1"></div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            {/* Apple Podcasts Player */}
            <div className="p-3 bg-white rounded-2xl shadow-sm border border-vintage-border transition-all duration-500 hover:shadow-md hover:border-vintage-black/30">
              <iframe 
                allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" 
                frameBorder="0" 
                height="450" 
                style={{ width: '100%', maxWidth: '660px', overflow: 'hidden', borderRadius: '12px', backgroundColor: 'transparent' }} 
                sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" 
                src="https://embed.podcasts.apple.com/us/podcast/beating-sisyphus-how-emerging-markets-overcome-the/id1855339237">
              </iframe>
            </div>

            {/* Spotify Player */}
            <div className="p-3 bg-white rounded-2xl shadow-sm border border-vintage-border transition-all duration-500 hover:shadow-md hover:border-vintage-black/30">
              <iframe 
                data-testid="embed-iframe" 
                style={{ borderRadius: '12px', backgroundColor: 'transparent' }} 
                src="https://open.spotify.com/embed/show/7DOx0zfgbVNiluDSoQJCmI?utm_source=generator&theme=0" 
                width="100%" 
                height="450" 
                frameBorder="0" 
                allowFullScreen={false} 
                allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
                loading="lazy">
              </iframe>
            </div>
          </div>
        </section>

        {/* About Section */}
        <section className="w-full">
          <div className="flex items-center justify-center gap-6 mb-12 w-full max-w-2xl mx-auto">
            <div className="h-px bg-vintage-border flex-1"></div>
            <h2 className="font-serif text-3xl md:text-4xl italic text-vintage-black">
              About the Show
            </h2>
            <div className="h-px bg-vintage-border flex-1"></div>
          </div>

          <div className="max-w-3xl mx-auto text-center mb-16">
            <p className="font-serif text-lg md:text-xl leading-relaxed text-vintage-black/90">
              Beating Sisyphus brings together leaders across economics, tech, finance, policy, and entrepreneurship to explore how innovation emerges under pressure. Through deep, intellectually honest conversations, we uncover the strategies, mindsets, and systems that allow emerging markets to overcome barriers and build lasting growth.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-16">
            {/* Host 1 */}
            <div className="flex flex-col">
              <div className="w-full max-w-[280px] mb-8 overflow-hidden rounded-2xl border border-vintage-border shadow-sm mx-auto md:mx-0 relative group bg-vintage-border/30">
                <div className="absolute inset-0 bg-vintage-red/20 mix-blend-multiply opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-10 pointer-events-none"></div>
                <img 
                  src={`${import.meta.env.BASE_URL}Casanova_Lourdes_.lc683_Johnson_DONE.jpg`} 
                  alt="Lourdes Casanova" 
                  className="w-full aspect-[4/5] object-cover grayscale group-hover:grayscale-0 transition-all duration-700 block"
                />
              </div>
              <div className="flex items-center justify-between border-b border-vintage-border pb-4 mb-6">
                <h3 className="font-serif text-2xl font-bold text-vintage-black">Lourdes Casanova</h3>
                <a href="https://www.linkedin.com/in/lourdescasanova" target="_blank" rel="noopener noreferrer" className="text-vintage-black/60 hover:text-vintage-red transition-colors">
                  <Linkedin size={20} />
                </a>
              </div>
              <div className="font-sans text-sm leading-relaxed text-vintage-black/80 space-y-4">
                <p>Lourdes Casanova is the Gail and Roberto Cañizares Director of the <a href="https://business.cornell.edu/centers-institutes/emerging-markets/" target="_blank" rel="noopener noreferrer" className="text-vintage-red hover:text-vintage-black underline decoration-vintage-red/30 hover:decoration-vintage-black transition-colors font-medium">Cañizares Center for Emerging Markets</a> and senior lecturer at the Samuel Curtis Johnson Graduate School of Management at Cornell University. Formerly of the strategy department at INSEAD, she specializes in international business with a focus on Latin America and multinationals from emerging markets.</p>
                <p>In 2014 and 2015, Casanova was named as one of the 50 most influential Iberoamerican intellectuals by Esglobal. She is a member of the board of directors of Boyce Thompson Institute.</p>
                <p>Casanova is a Fulbright Scholar who holds a PhD from Universidad de Barcelona and MA from the University of Southern California.</p>
              </div>
            </div>

            {/* Host 2 */}
            <div className="flex flex-col">
              <div className="w-full max-w-[280px] mb-8 overflow-hidden rounded-2xl border border-vintage-border shadow-sm mx-auto md:mx-0 relative group bg-vintage-border/30">
                <div className="absolute inset-0 bg-vintage-red/20 mix-blend-multiply opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-10 pointer-events-none"></div>
                <img 
                  src={`${import.meta.env.BASE_URL}Headshot.jpeg`} 
                  alt="Thomas Riveros" 
                  className="w-full aspect-[4/5] object-cover grayscale group-hover:grayscale-0 transition-all duration-700 block"
                />
              </div>
              <div className="flex items-center justify-between border-b border-vintage-border pb-4 mb-6">
                <h3 className="font-serif text-2xl font-bold text-vintage-black">Thomas Riveros</h3>
                <a href="https://www.linkedin.com/in/thomas-riveros-336b992a9" target="_blank" rel="noopener noreferrer" className="text-vintage-black/60 hover:text-vintage-red transition-colors">
                  <Linkedin size={20} />
                </a>
              </div>
              <div className="font-sans text-sm leading-relaxed text-vintage-black/80 space-y-4">
                <p>Thomas Riveros ’27 is an undergraduate at Cornell University majoring in economics with a minor in business. He is passionate about finance, emerging markets and macroeconomics. He is the co-host of “Beating Sisyphus,” a podcast that brings on experts from different industries to discuss how emerging markets succeed under pressure.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Episode Insights — Live Substack RSS Feed */}
        <section className="w-full mt-24">
          <div className="flex items-center justify-center gap-6 mb-12 w-full max-w-2xl mx-auto">
            <div className="h-px bg-vintage-border flex-1"></div>
            <h2 className="font-serif text-3xl md:text-4xl italic text-vintage-black">
              Episode Insights
            </h2>
            <div className="h-px bg-vintage-border flex-1"></div>
          </div>
          <div className="max-w-3xl mx-auto">
            <SubstackFeed />
          </div>
        </section>

        {/* Newsletter Signup */}
        <section className="w-full mt-24">
          <div className="flex items-center justify-center gap-6 mb-12 w-full max-w-2xl mx-auto">
            <div className="h-px bg-vintage-border flex-1"></div>
            <h2 className="font-serif text-3xl md:text-4xl italic text-vintage-black">
              Stay in the Loop
            </h2>
            <div className="h-px bg-vintage-border flex-1"></div>
          </div>
          <div className="max-w-3xl mx-auto">
            <div className="bg-white rounded-2xl border border-vintage-border shadow-sm p-8 md:p-12 text-center">
              <p className="font-serif text-lg italic text-vintage-black/70 mb-8 max-w-xl mx-auto">
                Get episode insights, analysis, and reflections delivered directly to your inbox — free.
              </p>
              <iframe
                src="https://beatingsisyphus.substack.com/embed"
                width="100%"
                height="150"
                style={{ border: '1px solid var(--color-vintage-border)', borderRadius: '12px', background: 'white', maxWidth: '480px', margin: '0 auto', display: 'block' }}
                frameBorder="0"
                scrolling="no"
                title="Subscribe to Beating Sisyphus on Substack"
              />
              <p className="mt-6 font-sans text-xs text-vintage-black/40 tracking-wide">
                No spam. Unsubscribe anytime.
              </p>
            </div>
          </div>
        </section>

      </main>

      <footer className="w-full py-12 text-center border-t border-vintage-border mt-auto flex flex-col items-center gap-4">
        <p className="font-serif italic text-vintage-black/70 text-sm">
          © {new Date().getFullYear()} Beating Sisyphus. All rights reserved.
        </p>
      </footer>
    </div>
  );
}

function PlatformLink({ href, icon, name }: { href: string, icon: React.ReactNode, name: string }) {
  return (
    <a 
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group flex items-center gap-3 px-8 py-3 rounded-full border border-vintage-black/20 bg-white/50 backdrop-blur-sm text-vintage-black hover:bg-vintage-red hover:text-vintage-cream hover:border-vintage-red transition-all duration-300 shadow-sm"
    >
      <span className="opacity-70 group-hover:opacity-100 transition-opacity">
        {icon}
      </span>
      <span className="font-sans text-xs tracking-[0.2em] uppercase font-medium mt-[2px]">
        {name}
      </span>
    </a>
  );
}

